# Generated by Django 3.2.16 on 2024-12-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentThroughTg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=12, verbose_name='Номер телефона для связи')),
                ('name', models.CharField(max_length=64, verbose_name='Как обращаться при звонке')),
                ('desired_time', models.CharField(max_length=128, verbose_name='Удобное клиенту время для звонка')),
            ],
            options={
                'verbose_name': 'запись из телеграма',
                'verbose_name_plural': 'Записи из телеграма',
            },
        ),
    ]
