# Generated by Django 3.2.16 on 2024-12-12 07:25

import autos.validators
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('popular', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'марка',
                'verbose_name_plural': 'Марки',
                'ordering': ['-popular'],
            },
        ),
        migrations.CreateModel(
            name='AutoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='autos.autobrand')),
            ],
            options={
                'verbose_name': 'модель',
                'verbose_name_plural': 'Модели',
            },
        ),
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(blank=True, help_text='Введите корректный ГРЗ в формате X999XX99 или X999XX199.', max_length=9, unique=True, validators=[autos.validators.plate_validator], verbose_name='ГРЗ')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autos', to='autos.autobrand', verbose_name='Марка авто')),
                ('model', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='brand', chained_model_field='brand', on_delete=django.db.models.deletion.CASCADE, to='autos.automodel', verbose_name='Модель авто')),
            ],
            options={
                'verbose_name': 'автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
    ]
